name: Checkstyle
description: 'Run checkstyle'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run checkstyle
      uses: dbelyaev/action-checkstyle@v0.6.1
      with:
        checkstyle_config: ./cision_checks.xml
        checkstyle_version: 9.2
        filter_mode: nofilter
        github_token: ${{ secrets.github_token }}
        level: warning
        reporter: github-pr-review

