name: Send Slack notification on pull request
on:
  workflow_call:
    secrets:
      UCP_WEBHOOK:
        required: true
  pull_request:
    types: [ opened, reopened ]
jobs:
  slack_PR_notification:
    runs-on: [ self-hosted, macOS, X64  ]
    if: ${{ github.base_ref == 'main'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Read value from file
        run: |
          # Read the value from the file
          VALUE=$(cat my_value.txt)
          echo "The value is: $VALUE"
          
