name: Send Slack notification on pull request
on:
  workflow_call:
    secrets:
      UCP_WEBHOOK:
        required: true
  pull_request:
    types: [ opened, reopened ]

jobs:
  slack_PR_notification:
    runs-on: [ self-hosted, macOS, X64]
    if: ${{ github.base_ref == 'main'}}
    steps:
      - name: Get user's e-mail
        id: user_email
        run: |
          git fetch
          echo "email=$(git log -n 1 --pretty=format:%ae remotes/origin/${{ github.head_ref }})" >> $GITHUB_ENV
      - name: Find Slack user
        if: ${{ !contains(env.email, '@users.noreply')}}
        id: find-slack-user
        uses: scribd/find-slack-user-action@v1
        with:
          email: ${{env.email}}
          slack-token: ${{ secrets.SLACK_API_TOKEN }}
      - name: Notify Slack on pull requests using Slack username
        if: ${{ !contains(env.email, '@users.noreply') && steps.find-slack-user.outputs.found-user}}
        run: |
          echo "${{env.email}}"
          echo "${{steps.find-slack-user.outputs.found-user}}"
      - name: Notify Slack on pull requests using github username
        if: ${{ contains(env.email, '@users.noreply') || env.email == '' || !steps.find-slack-user.outputs.found-user}}
        run: |
          echo "${{env.email}}"
