name: Send Slack notification on pull request
on:
  workflow_call:
    secrets:
      UCP_WEBHOOK:
        required: true
  pull_request:
    types: [ opened, reopened ]
jobs:
  slack_PR_notification:
    runs-on: [ self-hosted, macOS, X64  ]
    if: ${{ github.base_ref == 'main'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read file content
        id: read_file
        run: |
          CONTENT=$(cat ${{ github.workspace }}/.temp/temp.json)
          echo $CONTENT

      - name: Show file content
        run: |
          echo "File content: ${{ steps.read_file.outputs.stdout }}"
          
