name: Send Slack notification on pull request
on:
  workflow_call:
    secrets:
      UCP_WEBHOOK:
        required: true
  pull_request:
    types: [ opened, reopened ]
jobs:
  slack_PR_notification:
    runs-on: [ self-hosted, macOS, X64  ]
    if: ${{ github.base_ref == 'main'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get user's e-mail
        id: user_email
        run: |
          git checkout origin/${{ github.head_ref }}
          echo email=$(git log -n 1 --pretty=format:%ae)
          echo "email=$email" >> $GITHUB_ENV
          
          
      - name: get
        run: |
          echo "${{env.email}}"
#      - name: Get variable
#        id: http_request
#        run: |
#          response=$(curl --request GET \
#          --url https://api.github.com/repos/test-org-alexnad/ok/actions/variables/${{github.actor}} \
#          --header 'Authorization: Bearer ${{secrets.PAT}}' \
#          --header 'content-type: application/json' \
#          --fail)
#          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
#          echo $response >> $GITHUB_ENV
#          echo "EOF" >> $GITHUB_ENV
#
#      - name: Parse JSON response
#        id: parse_json
#        run: |
#          email=$(echo '${{ env.MULTI_LINES_TEXT_ENV_VAR }}' | jq -r '.email')
#          echo "email=$email" >> $GITHUB_ENV
#
#      - name: Use parsed email
#        run: |
#          echo "Parsed email: ${{ env.email }}"

