name: Send Slack notification on pull request
on:
  workflow_call:
    secrets:
      UCP_WEBHOOK:
        required: true
  pull_request:
    types: [ opened, reopened ]
jobs:
  slack_PR_notification:
    runs-on: [ self-hosted, macOS, X64  ]
    permissions: read-all
    if: ${{ github.base_ref == 'main'}}
    steps:
      - name: Generate a token
        id: generate_token
        run: |
          echo "${{ github.event.sender.email }}"
          
