name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ self-hosted, macOS, X64  ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store value
        run: |
          STATUS=$(curl -o /dev/null --write-out "%{http_code}" -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/actions/variables \
          -d '{"name":"${{github.author}}","email":"${{github.event.pusher.email}}"}')
          echo "API Response Status: $STATUS"


