name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ self-hosted, macOS, X64  ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store value
        run: |
          response=$(curl --request GET \
          --url https://api.github.com/test-org-alexnad/ok/actions/secrets/test \
          --header 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
          --header 'content-type: application/json' \
          --fail)
          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          echo $response >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

