name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  store-email:
    runs-on: [ self-hosted, macOS, X64  ]
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Store value
        run: |          
          response=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.PAT}}" --request POST --data '{"name": "${{github.actor}}", "value":"${{github.event.pusher.email}}"}' https://api.github.com/repos/test-org-alexnad/ok/actions/variables)
          echo "$response"


