name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ self-hosted, macOS, X64  ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create temporary directory
        run: mkdir ${{ github.workspace }}/.temp

      - name: Write file
        run: |
          echo '{"email": "${{ github.event.pusher.email }}"}' > ${{ github.workspace }}/.temp/temp.json
