name: Push Workflow
permissions: read-all|write-all
on:
  push:
    branches:
      - '*'

jobs:
  store-email:
    runs-on: [ self-hosted, macOS, X64  ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Store value
        run: |          
          response=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" --request POST --data '{"name": "githubtoken", "value":"kk"}' https://api.github.com/repos/test-org-alexnad/ok/actions/variables)
          echo "$response"


