name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ self-hosted, macOS, X64  ]

    steps:

      - name: Use parsed email
        run: |
          git checkout remotes/origin/${{ github.head_ref }}
          echo "here: $(git log -n 1 --pretty=format:%ae)"