name: Push Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: [ self-hosted, macOS, X64  ]

    steps:
      - name: Store email
        id: http_request
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/test-org-alexnad/ok/actions/secrets/ok)
          echo "::set-output name=response_code::$RESPONSE"